name: Lemuel De Los Santos
email: lemueld6200@afsenyc.org
github_username: lemueld6200
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
- jemoji
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
- jekyll-mentions
- jekyll-redirect-from
paginate: 10
paginate_path: "/blog/page:num/"

theme: jekyll-theme-hacker