name: Lemuel De Los Santos
email: lemueld6200@afsenyc.org
github_username: lemueld6200
markdown: kramdown
theme: minima
permalink: /blog/:year/:month/:day/:title
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
paginate: 5
paginate_path: "/blog/page:num/"
